openapi: 3.0.3
info:
  title: Common API Errors Schema
  version: 1.0.0

paths: {}

components:
  schemas:
    ApiError:
      type: object
      required:
        - status
        - error
        - message
      properties:
        status:
          type: integer
          example: 404
        error:
          type: string
          example: Not Found
        message:
          type: string
          example: Account not found