openapi: 3.0.3
info:
  title: Accounts
  description: An API to manage user accounts
  version: 1.0.0

paths:
  /accounts:
    get:
      summary: Retrieve a list of accounts
      responses:
        '200':
          description: A JSON array of account names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Create a new account
      requestBody:
        description: Account object that needs to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Account created successfully
        '400':
          description: Invalid input
components:
  schemas:
    AccountNotFoundError:
      allOf:
        - $ref: '../common/errors.yaml#/components/schemas/ApiError'
        - type: object
          properties:
            accountId:
              type: string